# Generated by Django 2.1.5 on 2019-01-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email_adr',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
